packages:
  - "nuxtjs0"
  - "nuxtjs1"
  - "nuxtjs2"
  - "nuxtjs3"
  - "nuxtjs4"
  - "nuxtjs5"
  - "nuxtjs6"
  - "nuxtjs7"
  - "nuxtjs8"
  - "nuxtjs9"


  # 工具 =====================================================
  - "Tools"
#首次gitbash设置邮箱和用户名0
#git config --global user.email "1311192345@qq.com"
#git config --global user.name "astmain"

#git取消追踪          git rm --cached *.db
#git取消追踪          git rm --cached D:\AAA\dayu_system_03\dayu04_end\src\db_orm_prisma\db_dev_sqlited.db

#1绑定文件            git init && git remote add origin  git@github.com:astmain/sys_nestjs.git

#强制上传             echo "确定:强制上传吗?" && TIMEOUT /T 60 && echo "如果确定:请回车" && git add . && git commit -m "强制上传" && git push -f origin  master

#本地分支跟踪远程分支  git branch --set-upstream-to=origin/master master

#nuxt网络问题 
# 在 C:\Windows\System32\drivers\etc\hosts 文件中添加下面内容
#  185.199.108.133 raw.githubusercontent.com





